source :gemcutter

gem 'will_paginate', '2.3.12'
gem 'paperclip', '2.3.1.1'
gem 'aws-s3', '0.6.2'
gem 'acts_as_list', '0.1.2'
gem 'responds_to_parent', '1.0.20091013'
gem 'yaml_db', '0.1.0'
gem 'rubypants'
gem 'bluecloth'
gem 'sanitize'
gem 'fastercsv'
gem 'calendar_date_select'
gem 'rack', '1.1.0'
gem 'radiant'
gem 'state_machine'
gem 'pg'
gem 'rails'
gem 'authlogic'
gem 'memcached-northscale', :require => 'memcached'
gem 'mollom'

